CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS tg_users
(
ID INT PRIMARY KEY,
TG_ID INT,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TG_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO tg_users VALUES (?, ?, ?, ?, ?)
"""

SELECT_USER_QUERY = """
SELECT * FROM tg_users
"""
